stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: miranmuthanna93/python-image
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker
  services:
    - docker:dind
  alias: thedockerhost
  script:
    - docker --version
    - docker pull alpine
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE_NAME


deploy:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws ecs update-service --cluster Python-ECS --service python-service --force-new-deployment
