image: python:3.9

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - pip install -r requirements.txt
    - python setup.py build
    # Additional build commands if necessary

deploy:
  stage: deploy
  image:
    name: python:3.9
    entrypoint: [""]
  script:
    - apt-get update && apt-get install -y curl jq
    - curl -L "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker build -t miranmuthanna93/python-image .
    - docker push miranmuthanna93/python-image
    - ecs_deploy

