stages:
  - build
  - deploy

build:
  stage: build
  image: miranmuthanna93/python-image
  services:
    - docker:19-dind
  script:
    - docker build -t miranmuthanna93/python-image .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push miranmuthanna93/python-image

deploy:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws ecs update-service --cluster Python-ECS --service python-service --force-new-deployment
