stages:
  - build
  - artifact
  - deploy

variables:
  IMAGE_NAME: my-app
  TASK_DEFINITION_NAME: python-ecs
  SERVICE_NAME: python-ecs-service
  CLUSTER_NAME: python-ecs
  AWS_REGION: us-east-1

build:
  stage: build
  image: python:3.8
  script:
    - apt-get update -y && apt-get install -y zip
    - pip install -r requirements.txt
    - python setup.py install

artifact:
  stage: artifact
  image: ubuntu:latest
  script:
    - apt-get update -y && apt-get install -y zip
    - zip -r app.zip . -x '*.git*'
  artifacts:
    paths:
      - app.zip

deploy:
  stage: deploy
  image: python:3.8
  before_script:
    - apt-get update -y && apt-get install -y awscli
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
